Changing permissions and adding more comments

diff --git a/base_external/rootfs_overlay/etc/init.d/S98lddmodules b/base_external/rootfs_overlay/etc/init.d/S98lddmodules
--- a/base_external/rootfs_overlay/etc/init.d/S98lddmodules
+++ b/base_external/rootfs_overlay/etc/init.d/S98lddmodules
@@ -1,151 +1,170 @@
 #!/bin/sh
 
-scull_module="scull"
-scull_device="scull"
+# Define module and device names
+scullModuleName="scull"
+scullDeviceName="scull"
 
-faulty_module="faulty"
-faulty_device="faulty"
+faultyModuleName="faulty"
+faultyDeviceName="faulty"
 
-hello_module="hello"
-hello_device="hello"
+helloModuleName="hello"
+helloDeviceName="hello"
 
-mode="664"
+# Define mode
+accessMode="664"
 
-
-function load_scull_dev()
-{
-    if [ ${#} -ne 1 ]; then 
+# Function to load scull device
+initializeScullDevice() {
+    # Check if the major number is provided
+    if [ $# -ne 1 ]; then 
         echo "Major number required!"
         exit 1
     fi
 
-    major=${1}
+    majorNumber=$1
 
     # Remove stale nodes and replace them, then give gid and perms
     # Usually the script is shorter, it's scull that has several devices in it.
 
-    rm -f /dev/${scull_device}[0-3]
-    mknod /dev/${scull_device}0 c $major 0
-    mknod /dev/${scull_device}1 c $major 1
-    mknod /dev/${scull_device}2 c $major 2
-    mknod /dev/${scull_device}3 c $major 3
-    ln -sf ${scull_device}0 /dev/${scull_device}
-    chmod $mode  /dev/${scull_device}[0-3]
+    # Remove old device nodes
+    rm -f /dev/${scullDeviceName}[0-3]
 
-    rm -f /dev/${deviscull_devicece}pipe[0-3]
-    mknod /dev/${scull_device}pipe0 c $major 4
-    mknod /dev/${scull_device}pipe1 c $major 5
-    mknod /dev/${scull_device}pipe2 c $major 6
-    mknod /dev/${scull_device}pipe3 c $major 7
-    ln -sf ${scull_device}pipe0 /dev/${device}pipe
-    chmod $mode  /dev/${scull_device}pipe[0-3]
+    # Create new device nodes
+    mknod /dev/${scullDeviceName}0 c $majorNumber 0
+    mknod /dev/${scullDeviceName}1 c $majorNumber 1
+    mknod /dev/${scullDeviceName}2 c $majorNumber 2
+    mknod /dev/${scullDeviceName}3 c $majorNumber 3
 
-    rm -f /dev/${scull_device}single
-    mknod /dev/${scull_device}single  c $major 8
-    chmod $mode  /dev/${scull_device}single
+    # Create a symbolic link to the first device node
+    ln -sf ${scullDeviceName}0 /dev/${scullDeviceName}
 
-    rm -f /dev/${scull_device}uid
-    mknod /dev/${scull_device}uid   c $major 9
-    chmod $mode  /dev/${scull_device}uid
+    # Set the access permissions for the device nodes
+    chmod $accessMode  /dev/${scullDeviceName}[0-3]
 
-    rm -f /dev/${scull_device}wuid
-    mknod /dev/${scull_device}wuid  c $major 10
-    chmod $mode  /dev/${scull_device}wuid
+    # Repeat the above steps for the pipe, single, uid, wuid, and priv devices
 
-    rm -f /dev/${scull_device}priv
-    mknod /dev/${scull_device}priv  c $major 11
-    chmod $mode  /dev/${scull_device}priv
+    rm -f /dev/${scullDeviceName}pipe[0-3]
+    mknod /dev/${scullDeviceName}pipe0 c $majorNumber 4
+    mknod /dev/${scullDeviceName}pipe1 c $majorNumber 5
+    mknod /dev/${scullDeviceName}pipe2 c $majorNumber 6
+    mknod /dev/${scullDeviceName}pipe3 c $majorNumber 7
+    ln -sf ${scullDeviceName}pipe0 /dev/${scullDeviceName}pipe
+    chmod $accessMode  /dev/${scullDeviceName}pipe[0-3]
 
-    echo "module: $scull_module loaded."
+    rm -f /dev/${scullDeviceName}single
+    mknod /dev/${scullDeviceName}single  c $majorNumber 8
+    chmod $accessMode  /dev/${scullDeviceName}single
+
+    rm -f /dev/${scullDeviceName}uid
+    mknod /dev/${scullDeviceName}uid   c $majorNumber 9
+    chmod $accessMode  /dev/${scullDeviceName}uid
+
+    rm -f /dev/${scullDeviceName}wuid
+    mknod /dev/${scullDeviceName}wuid  c $majorNumber 10
+    chmod $accessMode  /dev/${scullDeviceName}wuid
+
+    rm -f /dev/${scullDeviceName}priv
+    mknod /dev/${scullDeviceName}priv  c $majorNumber 11
+    chmod $accessMode  /dev/${scullDeviceName}priv
+
+    echo "module: $scullModuleName loaded."
 }
 
-function unload_scull_dev()
-{
-    rmmod $scull_device $* || exit 1
+# Function to unload scull device
+deinitializeScullDevice() {
+    # Remove the scull module
+    rmmod $scullDeviceName $* || exit 1
+
     # Remove stale nodes
-
-    rm -f /dev/${scull_device} /dev/${scull_device}[0-3] 
-    rm -f /dev/${scull_device}priv
-    rm -f /dev/${scull_device}pipe /dev/${scull_device}pipe[0-3]
-    rm -f /dev/${scull_device}single
-    rm -f /dev/${scull_device}uid
-    rm -f /dev/${scull_device}wuid
+    rm -f /dev/${scullDeviceName} /dev/${scullDeviceName}[0-3] 
+    rm -f /dev/${scullDeviceName}priv
+    rm -f /dev/${scullDeviceName}pipe /dev/${scullDeviceName}pipe[0-3]
+    rm -f /dev/${scullDeviceName}single
+    rm -f /dev/${scullDeviceName}uid
+    rm -f /dev/${scullDeviceName}wuid
 }
 
-function load_faulty_dev()
-{
-    if [ ${#} -ne 1 ]; then 
+# Function to load faulty device
+initializeFaultyDevice() {
+    # Check if the major number is provided
+    if [ $# -ne 1 ]; then 
         echo "Major number required!"
         exit 1
     fi
 
-    echo "Remove any existing /dev node for /dev/${faulty_device}"
-    rm -f /dev/${faulty_device}
-    echo "Add a node for our device at /dev/${faulty_device} using mknod"
-    mknod /dev/${faulty_device} c $major 0
-    echo "Change access mode to ${mode}"
-    chmod $mode  /dev/${faulty_device}
-    echo "module: $faulty_module loaded."
+    majorNumber=$1
+
+    # Remove any existing /dev node for /dev/${faultyDeviceName}
+    rm -f /dev/${faultyDeviceName}
+
+    # Add a node for our device at /dev/${faultyDeviceName} using mknod
+    mknod /dev/${faultyDeviceName} c $majorNumber 0
+
+    # Change access mode to ${accessMode}
+    chmod $accessMode  /dev/${faultyDeviceName}
+
+    echo "module: $faultyModuleName loaded."
 }
 
-function unload_faulty_dev()
-{
-    # invoke rmmod with all arguments we got
-    rmmod $faulty_module || exit 1
+# Function to unload faulty device
+deinitializeFaultyDevice() {
+    # Remove the faulty module
+    rmmod $faultyModuleName || exit 1
 
     # Remove stale nodes
-
-    rm -f /dev/${faulty_device}
+    rm -f /dev/${faultyDeviceName}
 }
 
-
-if test ${#} -ne 1
-then
+# Main script
+if [ $# -ne 1 ]; then
     echo "Wrong number of parameters"
     exit 1
 fi
 
-case ${1} in
+case $1 in
 "start")
     echo "Running load ldd drivers daemon"
-    echo "Load scull module, exit on failure"
-    insmod /lib/modules/$(uname -r)/extra/$scull_module.ko $* || exit 1
-    echo "Get the major number (allocated with allocate_chrdev_region) from /proc/devices"
-    major=$(awk "\$2==\"$scull_module\" {print \$1}" /proc/devices)
-    echo "scull major number is: ${major}"
+
+    # Load scull module, exit on failure
+    insmod /lib/modules/$(uname -r)/extra/$scullModuleName.ko $* || exit 1
+
+    # Get the major number (allocated with allocate_chrdev_region) from /proc/devices
+    majorNumber=$(awk "\$2==\"$scullModuleName\" {print \$1}" /proc/devices)
+    echo "scull major number is: ${majorNumber}"
 
     # load scull device
-    load_scull_dev "$major"
+    initializeScullDevice "$majorNumber"
 
-    echo "Load faulty module, exit on failure"
-    insmod /lib/modules/$(uname -r)/extra/$faulty_module.ko $* || exit 1
-    echo "Get the major number (allocated with allocate_chrdev_region) from /proc/devices"
-    major=$(awk "\$2==\"$faulty_module\" {print \$1}" /proc/devices)
-    echo "faulty major number is: ${major}"
+    # Load faulty module, exit on failure
+    insmod /lib/modules/$(uname -r)/extra/$faultyModuleName.ko $* || exit 1
+
+    # Get the major number (allocated with allocate_chrdev_region) from /proc/devices
+    majorNumber=$(awk "\$2==\"$faultyModuleName\" {print \$1}" /proc/devices)
+    echo "faulty major number is: ${majorNumber}"
 
     # load faulty device
-    load_faulty_dev "$major"
+    initializeFaultyDevice "$majorNumber"
 
     # basic modprobe of hello driver
     cd /lib/modules/$(uname -r)/extra/
-    modprobe $hello_module.ko $* || exit 1
+    modprobe $helloModuleName.ko $* || exit 1
 
     ;;
 "stop")
     echo "Stopping load ldd drivers daemon"
 
     # unload scull device
-    unload_scull_dev "$major"
+    deinitializeScullDevice "$majorNumber"
 
     # unload faulty device
-    unload_faulty_dev
+    deinitializeFaultyDevice
     
     # basic rmmod of hello driver
-    rmmod /lib/modules/$(uname -r)/extra/$hello_module.ko || exit 1
+    rmmod /lib/modules/$(uname -r)/extra/$helloModuleName.ko || exit 1
 
     ;;
 *)
-    echo "Invalid option \"${1}\""
+    echo "Invalid option \"$1\""
     exit 2
     ;;
 esac
